config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :transactions
  resources :merchandises
  resources :one_day_passes
  resources :pass_categories
  resources :memberships
  resources :members
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'memberships#index'
end

app/controllers/one_day_passes_controller.rb
class OneDayPassesController < ApplicationController
  before_action :set_one_day_pass, only: [:show, :edit, :update, :destroy]

  # GET /one_day_passes
  # GET /one_day_passes.json
  def index
    @one_day_passes = OneDayPass.all
  end

  # GET /one_day_passes/1
  # GET /one_day_passes/1.json
  def show
  end

  # GET /one_day_passes/new
  def new
    @one_day_pass = OneDayPass.new
    @sale = Sale.new
  end

  # GET /one_day_passes/1/edit
  def edit
  end

  # POST /one_day_passes
  # POST /one_day_passes.json
  def create
    @one_day_pass = current_member.one_day_passes.build(one_day_pass_params)
    @sale = current_member.sales.build(date: Date.today)

    ActiveRecord::Base.transaction do
      @one_day_pass.save!
      @sale.save!
    end

    redirect_to @one_day_pass, notice: 'One day pass was successfully created.' 

  rescue ActiveRecord::RecordInvalid => e
    pp e
    return render :new, notice: "Something went wrong" 
  end

  # PATCH/PUT /one_day_passes/1
  # PATCH/PUT /one_day_passes/1.json
  def update
    respond_to do |format|
      if @one_day_pass.update(one_day_pass_params)
        format.html { redirect_to @one_day_pass, notice: 'One day pass was successfully updated.' }
        format.json { render :show, status: :ok, location: @one_day_pass }
      else
        format.html { render :edit }
        format.json { render json: @one_day_pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /one_day_passes/1
  # DELETE /one_day_passes/1.json
  def destroy
    @one_day_pass.destroy
    respond_to do |format|
      format.html { redirect_to one_day_passes_url, notice: 'One day pass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_one_day_pass
      @one_day_pass = OneDayPass.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def one_day_pass_params
      params.require(:one_day_pass).permit(:date, :pass_category_id)
    end

end

app/helpers/one_day_passes_helper.rb
module OneDayPassesHelper
end

app/views/one_day_passes/_form.html.erb
<%= form_with(model: one_day_pass, local: true) do |form| %>
  <% if one_day_pass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(one_day_pass.errors.count, "error") %> prohibited this one_day_pass from being saved:</h2>

      <ul>
        <% one_day_pass.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_of_pass %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :select_pass %>
    <%= form.collection_select(:pass_category_id, PassCategory.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <%
=begin%>
  how to create a hidden field?
 <td><%= one_day_pass.hidden_field member_id: @member.id %></td>
  <td><%= one_day_pass.collection_select(:pass_category_id, PassCategory.all, :id, :name) %></td> 
<%
=end%>


<% end %>

app/views/one_day_passes/edit.html.erb
<h1>Editing One Day Pass</h1>

<%= render 'form', one_day_pass: @one_day_pass %>

<%= link_to 'Show', @one_day_pass %> |
<%= link_to 'Back', one_day_passes_path %>

app/views/one_day_passes/index.html.erb
<div class='container'>
  <h1>One Day Passes</h1>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Member</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @one_day_passes.each do |one_day_pass| %>
        <tr>
          <td><%= one_day_pass.date %></td>
          <td><%= one_day_pass.member_id %></td>
          <td><%= link_to 'Show', one_day_pass %></td>
          <td><%= link_to 'Edit', edit_one_day_pass_path(one_day_pass) %></td>
          <td><%= link_to 'Destroy', one_day_pass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New One Day Pass', new_one_day_pass_path %>

app/views/one_day_passes/new.html.erb
<h1>New One Day Pass</h1>
<% if @sale.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: @sale.errors.count,
                 resource: @sale.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render 'form', one_day_pass: @one_day_pass %>

<%= link_to 'Back', one_day_passes_path %>

app/views/one_day_passes/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @one_day_pass.date %>
</p>

<p>
  <strong>Member:</strong>
  <%= @one_day_pass.member_id %>
</p>

<p>
  <strong>Pass Category:</strong>
  <%= @one_day_pass.pass_category_id %>
  <%= @one_day_pass.pass_category.name %>
  <%= @one_day_pass.pass_category.price %>
</p>

<%= link_to 'Edit', edit_one_day_pass_path(@one_day_pass) %> |
<%= link_to 'Back', one_day_passes_path %>